[versions]
apache-commonsIO = "2.16.1"
apache-plc4x = "0.12.0"
hivemq-edge-adapterSdk = "2024.5"
jackson = "2.17.1"
junit-jupiter = "5.10.3"
mockito = "5.12.0"
slf4j = "2.0.13"

[libraries]
apache-commonsIO = { module = "commons-io:commons-io", version.ref = "apache-commonsIO" }
hivemq-edge-adapterSdk = { module = "com.hivemq:hivemq-edge-adapter-sdk", version.ref = "hivemq-edge-adapterSdk" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
mockito-junitJupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
plc4j-api = { module = "org.apache.plc4x:plc4j-api", version.ref = "apache-plc4x" }
plc4j-s7 = { module = "org.apache.plc4x:plc4j-driver-s7", version.ref = "apache-plc4x" }
plc4j-ads = { module = "org.apache.plc4x:plc4j-driver-ads", version.ref = "apache-plc4x" }
plc4j-transport-raw-socket = { module = "org.apache.plc4x:plc4j-transport-raw-socket", version.ref = "apache-plc4x" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
